### ISSUE TITLE
could not find delimiter

### ISSUE THREAD

**Issue by nanjum88** [jorgelbg/dissect-tester#11]
Amazing tool @jorgelbg  (Thanks) - 

But how do we test the dissect patterns when we have values in quotes in the log event ?
 
I tried with the same Envoy example in the blog - 

Dissect Pattern - 
[%{timestamp}] "%{request}" %{status} - %{bytes_sent} "%{forwarded_ips}"
"%{user_agent}" "%{unknown_id}" "%{destination_host}" "%{destination_address}"

[2020-02-21T14:29:08.671Z] "GET /stats?format=prometheus&usedonly=1 HTTP/1.1"
200 - 0 105150 6 - "10.22.10.103" "Prometheus/2.7.0" "-" "10.22.10.121:12345" "-"

but get the following error  - 

sample: 0, error: could not find delimiter: `] "` in remaining: `GET /stats?format=prometheus&usedonly=1 HTTP/1.1"`, (offset: 28)

![image](https://user-images.githubusercontent.com/32209105/81494065-9c95db00-925a-11ea-98be-3e79cc30b3de.png)

**Comment by jorgelbg** [comment]
> Amazing tool @jorgelbg (Thanks) -

Thank you @nanjum88 

I believe that you have a couple of return lines both in your pattern/tokenizer & in your log sample. The UI doesn't remove any `\n` characters so the entire sample & tokenizer both need to go in a single line.

I tested by removing the new lines from your example and used this as the tokenizer: 
```
[%{timestamp}] "%{request}" %{status} - %{bytes_sent} "%{forwarded_ips}" "%{user_agent}" "%{unknown_id}" "%{destination_host}" "%{destination_address}"
```

and as the sample:
```
[2020-02-21T14:29:08.671Z] "GET /stats?format=prometheus&usedonly=1 HTTP/1.1" 200 - 0 105150 6 - "10.22.10.103" "Prometheus/2.7.0" "-" "10.22.10.121:12345" "-"
```

and this is the result:
```
{
  "bytes_sent": "0 105150 6 -",
  "destination_address": "-",
  "destination_host": "10.22.10.121:12345",
  "forwarded_ips": "10.22.10.103",
  "request": "GET /stats?format=prometheus&usedonly=1 HTTP/1.1",
  "status": "200",
  "timestamp": "2020-02-21T14:29:08.671Z",
  "unknown_id": "-",
  "user_agent": "Prometheus/2.7.0"
}
```

I think hat the problem was not the quotes but the new line characters itself, perhaps something to improve or at least to make more visible in the UI.
