### ISSUE TITLE
log sample won't accept input with '<'

### ISSUE THREAD

**Issue by pharrison007** [jorgelbg/dissect-tester#43]
The log sample seems to treat less than ('<') as a wildcard, so pasting any log content with such character (e.g. a weblogic server log: https://tekslate.com/weblogic-logging-filtering) will fail.
dissect pattern '####<%{Timestamp}> <%{Severity}> <%{Subsystem}> <%{MachineName}> <%{ServerName}> <%{ThreadID}> <%{UserID}> <%{TransactionID}> <%{ContextID}> <%{RawTimeValue}> <%{MessageID}> <%{MessageText}>'

You can manually retype the log text - this will work once, but if you click elsewhere then back to log sample it will be reformatted to replace 'special' chars with e.g. \&gt; \&lt; etc. which will then not parse
probably the same is the case with other 'special' chars.
I note this is problem with "log sample" but not with the dissect pattern

**Comment by jorgelbg** [comment]
@pharrison007 Thanks for opening the issue. I believe this is related to the use of a `div` with `contenteditable="true"` to emulate the `textarea` tag we were using before. I need to find a better way of handling this case.

**Comment by paketb0te** [comment]
@jorgelbg you likely already know, but just in case:

This appears to be triggered by the [clearContentEditableLine](https://github.com/jorgelbg/dissect-tester/blob/master/static/js/main.js#L98) function, but I guess the escaping is nessecary?

Maybe using [textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) instead of innerHTML would alleviate the need for escaping those characters?

Again, I am a complete novice in regards to HTML / JS, so please feel free to hit me with a cluestick in case that makes no sense :smile:

**Comment by jorgelbg** [comment]
FYI I deployed the new image to https://dissect-tester.jorgelbg.me/. I did some testing using the examples in this issue and in the linked blog post but it would be useful if someone else gives it a try. Feel free to reopen the issue.

**Comment by paketb0te** [comment]
@jorgelbg this solves the issue I have been observing, thanks!

**Comment by jorgelbg** [comment]
Nice @paketb0te thanks for confirming!
